CREATE TABLE SALES
(
    id         BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    order_no   VARCHAR(255),
    amount     BIGINT NOT NULL,
    order_date DATE,
    constraint SALES_INST_UN unique (order_no)
) ENGINE = InnoDB;

SELECT *
FROM SALES;

DROP TABLE SALES;

CREATE TABLE IF NOT EXISTS `SALES`
(
    ID         BIGINT NOT NULL AUTO_INCREMENT,
    AMOUNT     BIGINT NOT NULL,
    ORDER_DATE DATE,
    ORDER_NO   VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE = INNODB;